embedding_model: bge-m3
gitee_api_key: ""
model_name: x-ai/grok-4.1-fast:free
openrouter_api_key: ""
serper_api_key: ""
template: "Web search result:\n{context_str}\n\nInstructions: You are a/an {profile}.\
  \ Using the provided web search results, write a comprehensive and detailed reply\
  \ to the given query. \nMake sure to cite results using [number] notation after\
  \ the reference.\nAt the end of the answer, list the corresponding references with\
  \ indexes. Each reference should include:\n- The URL\n- A relevant quote from that\
  \ source (exactly as it appears in the search results)\n\nExample format:\n[1] https://example.com\n\
  \    \"Exact quote from the source that supports the information cited.\"\n\nAnswer\
  \ in language: {language}\nQuery: {query}\nOutput Format: {format}\nPlease organize\
  \ your output according to the Output Format. If the Output Format is empty, you\
  \ can ignore it."
